name: Compile LwM2M type definitions

on:
  push:
    branches:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm ci

      - name: Clone LwM2M object registry
        run:
          git clone https://github.com/OpenMobileAlliance/lwm2m-registry.git
          --depth 1

      - name: Run unit tests
        run: npm test

      - name: From XML to JSON
        run: |
          mkdir lwm2m-registry-json
          npx tsx cli/XMLtoJSON.ts ./lwm2m-registry ./lwm2m-registry-json

      - name: From JSON to TypeBox definition
        run: |
          mkdir typebox-definitions
          npx tsx cli/JSONtoTypeBox.ts ./lwm2m-registry-json ./typebox-definitions

      - name: Create LwM2M TypeBox definition object
        run: npx tsx ./src/TypeScript/createTypeboxDef

      - name: Create the JSON Schema
        run: npx tsx cli/generate-json-schema.ts

      - name: Create LwM2M TypeScript Types
        run: |
          npx tsx ./src/TypeScriptTypes/index.ts
          npx eslint --fix .

      - name: Format result
        run: npx prettier --write ./

      - name: Make sure result compiles
        run: npx tsc

      - name: Make sure example runs
        run: npx tsx ./example.ts
