name: Test and Release

on:
  push:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Keep npm cache around to speed up installs
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Clone LwM2M object registry
        run:
          git clone https://github.com/OpenMobileAlliance/lwm2m-registry.git
          --depth 1

      - name: Compile JS exports
        run: npx swc -d types-dist ./types

      - name: Run unit tests
        run: npm test

      - name: Create LwM2M types
        run: npx tsx cli/generate-types.ts

      - name: Create the JSON Schema
        run: npx tsx cli/generate-json-schema.ts

      - name: Format result
        run: npx prettier --write ./

      - name: Make sure result compiles
        run: npx tsc

      - name: Make sure example runs
        run: npx tsx ./example.ts

      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        continue-on-error: true
        run: npx semantic-release
